name: Build web
on: [push, pull_request]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4 # set up Java for Gradle
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install wasm-pack
        run: npm install -g wasm-pack
      - name: Build
        run: ./gradlew buildWeb
      - name: Checkout pages
        # Only run for the release branch
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v4
        with:
          ref: pages
          path: pages
      - name: Commit web content
        # Only run for the release branch
        if: github.ref == 'refs/heads/main'
        run: |
          # Remove existing files and copy new files
          ./gradlew refreshWebFiles
          # Set committer details (see actions/checkout README)
          cd pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          # Commit and push
          git add .
          git commit -m "Update files"
          git push
